In [1]:
import sys  ###policyevaluation1
sys.path.append('../scripts/')
from puddle_world import *

In [2]:
class PolicyEvaluator:
    def __init__(self, widths, lowerleft=np.array([-4, -4]).T, upperright=np.array([4, 4]).T):
        self.pose_min = np.r_[lowerleft, 0]
        self.pose_max = np.r_[upperright, math.pi*2] #thetaの範囲0〜2πで固定
        self.widths = widths
        
        self.index_nums = ((self.pose_max - self.pose_min)/self.widths).astype(int)

In [3]:
pe = PolicyEvaluator(np.array([0.2, 0.2, math.pi/18]).T) #PolicyEvaluatorのオブジェクトを生成
print(pe.index_nums)  #区間の個数を表示

[40 40 36]


In [4]:
#様々な座標のインデックスを求めてみましょう

pose = np.array([-4, -4, 0]).T
print( np.floor((pose - pe.pose_min)/pe.widths).astype(int) )

pose = np.array([2.9, -2, math.pi]).T
print (np.floor((pose - pe.pose_min)/pe.widths).astype(int) )

pose = np.array([-5, -2, math.pi/6]).T
print (np.floor((pose - pe.pose_min)/pe.widths).astype(int) )

[0 0 0]
[34 10 18]
[-5 10  3]
